---

- name: "add pgadmin repo debian | Download pgadmin packages signing key"
  ansible.builtin.get_url:
    url: "{{ pgadmin_apt_key_url }}"
    dest: /tmp/pgadmin.gpg
    mode: 0644
    validate_certs: false
    force: True
  register: pgadmin_apt_key_results
  until: pgadmin_apt_key_results is succeeded
  retries: 5
  delay: 5

- name: "add pgadmin repo debian | Install pgadmin packages signing key"   # noqa risky-shell-pipe
  ansible.builtin.shell: >-
    cat /tmp/pgadmin.gpg | sudo gpg --dearmor --yes -o {{ pgadmin_apt_keys_dir }}/pgadmin.gpg; rm -f /tmp/pgadmin.gpg
  changed_when: True
