---
- name: "add pgdg repo alpine | Ensure all required repos are enabled"
  ansible.builtin.replace:
    path: /etc/apk/repositories
    regexp: "{{ item }}"
    replace: '\1'
  with_items:
    - "{{ postgresql_repo }}"
