---
- name: "pgadmin packages redhat | Check required pgadmin rpm repo is available"
  ansible.builtin.uri:
    url: >-
      {{ postgresql_url }}pgadmin/pgadmin4/yum/{% if ansible_distribution == 'Fedora' %}fedora/fedora-{% else -%}
      redhat/rhel-{% endif %}{{ ansible_distribution_major_version }}-{{ ansible_architecture -}}
    validate_certs: "{{ ansible_python_version is version('2.7.5', '>=') }}"
  register: check_pgadmin_repo_url_results
  ignore_errors: True
  failed_when: check_pgadmin_repo_url_results.status == 404

- name: "pgadmin packages redhat | Set facts for pgadmin install"
  ansible.builtin.set_fact:
    firewall_port: 80
    firewall_state: "{% if check_pgadmin_repo_url_results.failed %}False{% else %}True{% endif %}"
    packages_to_install: "{% if check_pgadmin_repo_url_results.failed %}[]{% else %}{{ pgadmin_packages }}{% endif %}"
