---

- name: "purge pgdg repo redhat | Remove repository key"   # noqa ignore-errors
  ansible.builtin.rpm_key:
    key: "{{ postgresql_url }}repos/yum/RPM-GPG-KEY-PGDG"
    state: absent
    validate_certs: False
  ignore_errors: True
