---

- name: "purge pgdg repo debian | Remove PostgreSQL asc key"
  ansible.builtin.file:
    path: "{{ postgresql_apt_keys_dir }}/pgdg.asc"
    state: absent

- name: "purge pgdg repo debian | Purge debian repository"
  ansible.builtin.apt_repository:
    repo: "{{ postgresql_repo_file }}"
    state: absent