---

- name: "uninstall server redhat | Get postgresql dnf modules list"   # noqa risky-shell-pipe
  ansible.builtin.shell: dnf -qy module list | grep 'postgresql' || true
  register: dnf_postgresql_module_results
  changed_when: false
  when: ansible_pkg_mgr == 'dnf'

- name: "uninstall server redhat | Uninstall postgresql/server dnf module"
  ansible.builtin.command: dnf -qy module remove postgresql/server
  changed_when: true
  when: dnf_postgresql_module_results.stdout is defined and '[i]' in dnf_postgresql_module_results.stdout
