---

- name: "uninstall server | Include purge repo {{ ansible_os_family | lower }} tasks"
  ansible.builtin.include_tasks: purge_pgdg_repo_{{ ansible_os_family | lower }}.yml
  when: ansible_os_family != 'Alpine'

- name: "uninstall server | Include check firewall {{ ansible_os_family | lower }} tasks"
  ansible.builtin.include_tasks: includes_misc/check_firewall_{{ ansible_os_family | lower }}.yml
  when: ansible_os_family != 'Alpine'

- name: "uninstall server | Include uninstall {{ ansible_os_family | lower }} tasks"
  ansible.builtin.include_tasks: uninstall_server_{{ ansible_os_family | lower }}.yml
  when: ansible_os_family != 'Debian'

- name: "uninstall server | Include server packages {{ ansible_os_family | lower }} tasks"
  ansible.builtin.include_tasks: server_packages_{{ ansible_os_family | lower }}.yml

- name: "uninstall server | Purge packages"
  ansible.builtin.include_tasks: pkg_management/purge_{{ ansible_pkg_mgr }}.yml

- name: "uninstall server | Include firewall control {{ ansible_os_family | lower }} tasks"
  ansible.builtin.include_tasks: includes_misc/firewall_control_{{ ansible_os_family | lower }}.yml
  when: ansible_os_family != 'Alpine'

- name: "uninstall server | Cleanup related files and folders"
  ansible.builtin.file:
    path: "{{ postgresql_data_path }}"
    state: absent
  when: cleanup_data_directory

- name: "uninstall server | Include uninstall pgadmin tasks"
  ansible.builtin.include_tasks: uninstall_pgadmin.yml
  when: install_pgadmin
