ARG image_platform
ARG image_tag
FROM ${image_platform}:${image_tag}

RUN apk update; \
    apk add --no-cache sudo bash dbus python3 gnupg ca-certificates openrc coreutils iputils pcre2 tzdata; \
    mkdir -p /run/openrc; \
    touch /run/openrc/softlevel; \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf; \
    sed -i -e 's/#rc_sys=""/rc_sys="lxc"/g' -e 's/^#\(rc_logger="YES"\)$/\1/' /etc/rc.conf; \
    sed -i '/tty/d' /etc/inittab; \
    sed -i 's/hostname $opts/# hostname $opts/g' /etc/init.d/hostname; \
    sed -i 's/mount -t tmpfs/# mount -t tmpfs/g' /lib/rc/sh/init.sh

VOLUME ["/sys/fs/cgroup"]
ENTRYPOINT ["/sbin/init"]