FROM $MOLECULE_IMAGE

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       lsb-release \
       python3 \
       sudo \
       systemd \
       systemd-sysv \
       wget \
    && apt-get clean

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]