ARG image_platform
ARG image_tag
FROM ${image_platform}:${image_tag}

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        gnupg2 \
        software-properties-common \
        apt-utils \
        lsb-release \
        python3 \
        sudo \
        bash \
        systemd \
        dbus \
        iproute2; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]