FROM ubuntu:14.04

USER root
WORKDIR /root

ENV container docker
ENV DEBIAN_FRONTEND=noninteractive

SHELL [ "/bin/bash", "-c" ]

RUN apt-get -qq -y update && \
    apt-get -qq -y install --no-install-recommends apt-utils dialog && \
    apt-get -qq -y install \
        software-properties-common \
        apt-utils \
        sudo \
        python2.7 \
        init \
        util-linux && \
    add-apt-repository ppa:jonathonf/python-3.8 && \
    apt-get update && \
    apt-get install python3.8

STOPSIGNAL SIGRTMIN+3

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT [ "/sbin/init" ]