---
YAML_YAMLLINT_CONFIG_FILE: .yamllint
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: server_packages_redhat.yml

ANSIBLE_DIRECTORY: .
ANSIBLE_ANSIBLE_LINT_ARGUMENTS: --force-color

REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV_ANSIBLE_1,CKV_ANSIBLE_2,CKV_ANSIBLE_3,CKV2_ANSIBLE_1,CKV2_ANSIBLE_2

DISABLE_LINTERS:
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
