---
YAML_YAMLLINT_CONFIG_FILE: .yamllint
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: server_packages_redhat.yml
ANSIBLE_DIRECTORY: .
ANSIBLE_ANSIBLE_LINT_ARGUMENTS: --force-color -p
DISABLE_ERRORS_LINTERS:
  - SPELL_CSPELL
  - REPOSITORY_DEVSKIM
