---

namespace: alexanderbazhenoff
name: linux
version: 1.1.10
readme: README.md
authors:
  - Aleksandr Bazhenov <>
description: Various roles for Linux
license:
  - BSD-3-Clause
tags:
  - linux
  - monitoring
  - containers
  - backup
  - databases
dependencies:
  "community.general": "*"
  "community.postgresql": "*"
  "community.docker": '*'
  "ansible.posix": "*"
repository: https://github.com/alexanderbazhenoff/ansible-collection-linux
documentation: https://github.com/alexanderbazhenoff/ansible-collection-linux/wiki
homepage: https://galaxy.ansible.com/alexanderbazhenoff/ansible-collection-linux
issues: https://github.com/alexanderbazhenoff/ansible-collection-linux/issues
build_ignore: []
