---
- name: Converge
  hosts: bareos_servers
  become: true
  become_method: sudo

  tasks:
    - name: "default >>> converge | Include bareos role to install bareos-dir, -ui, -fd and -sd"
      ansible.builtin.include_role:
        name: alexanderbazhenoff.linux.bareos
      vars:
        role_action: install
        bareos_components: dir_webui
        postgresql_version:
          "{% if ansible_os_family == 'RedHat' and ansible_distribution_major_version | int == 8 -%}
          13{% else %}14{% endif %}"
        init_bareos_database: "{{ (ansible_os_family == 'RedHat') }}"
        debug_mode: true
