FROM jrei/systemd-ubuntu:16.04

USER root
WORKDIR /root

ENV container gitlab-runner
ENV DEBIAN_FRONTEND=noninteractive

SHELL [ "/bin/bash", "-c" ]

RUN apt-get -qq -y update && \
    apt-get -qq -y install --no-install-recommends apt-utils dialog && \
    apt-get -qq -y install \
        software-properties-common \
        apt-utils \
        sudo \
        python3 \
        dbus

STOPSIGNAL SIGRTMIN+3

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT [ "/lib/systemd/systemd" ]