---

dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: docker
platforms:

  - name: debian12-instance
    image: jrei/systemd-debian:12
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-debian
      image_tag: 12
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    groups:
      - bareos_servers
      - bareos_clients

  - name: ubuntu2004-instance
    image: jrei/systemd-ubuntu:20.04
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-ubuntu
      image_tag: 20.04
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    groups:
      - bareos_servers
      - bareos_clients

  - name: ubuntu2204-instance
    image: jrei/systemd-ubuntu:22.04
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-ubuntu
      image_tag: 22.04
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    groups:
      - bareos_servers
      - bareos_clients

  - name: oraclelinux9-instance
    image: oraclelinux:9
    dockerfile: dockerfile_redhat.j2
    buildargs:
      image_platform: oraclelinux
      image_tag: 9
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    groups:
      - bareos_servers
      - bareos_clients

scenario:
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - destroy
provisioner:
  name: ansible
  env:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  inventory:
    host_vars:
      debian12-instance:
        bareos_dir: oraclelinux9-instance
      ubuntu2204-instance:
        bareos_dir: ubuntu2004-instance
      ubuntu2004-instance:
        bareos_dir: ubuntu2204-instance
      oraclelinux9-instance:
        bareos_dir: debian12-instance
lint: |
    export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
    export PY_COLORS=1
    export ANSIBLE_FORCE_COLOR=1
    yamllint .
    ansible-lint .
    flake8 .
verifier:
  name: ansible
