---

- name: "install yum | Install packages"   # noqa package-latest
  ansible.builtin.yum:
    name: "{{ item.package }}"
    state: latest   # kics-scan ignore-line
    update_cache: true
    disablerepo: "{{ item.disable_repo | default(omit) }}"
    enablerepo: "{{ item.enable_repo | default(omit) }}"
    validate_certs: "{{ ansible_python_version is version('2.7.5', '>=') }}"
  register: install_results
  until: install_results is succeeded
  retries: 5
  delay: 5
  when: item.package | length > 0
  with_items:
    - "{{ packages_to_install }}"
