---

- name: "install dnf | Install packages"   # noqa package-latest
  ansible.builtin.dnf:
    name: "{{ item.package }}"
    state: latest   # kics-scan ignore-line
    update_cache: true
    disable_gpg_check: "{{ item.disable_gpg_check | default(false) }}"
  register: install_results
  until: install_results is succeeded
  retries: 5
  delay: 5
  when: item.package | length > 0
  with_items:
    - "{{ packages_to_install }}"
