---
- name: "install apt | Install packages" # noqa package-latest
  ansible.builtin.apt:
    name: "{{ item.package }}"
    state: latest # kics-scan ignore-line
    update_cache: True
  register: install_results
  until: install_results is succeeded
  retries: 5
  delay: 5
  when: item.package | length > 0
  with_items:
    - "{{ packages_to_install }}"
