---

postgresql_repo:
  - '^#(.*http(s?):\/\/dl-cdn\.alpinelinux\.org\/alpine\/v[0-9].+)'
  - '^#(.*http(s?):\/\/dl-cdn\.alpinelinux\.org\/alpine\/edge\/.+)'

postgresql_packages:
  - "{% if install_psycopg2 %}py{{ (ansible_python.version.major == 3) | ternary('3', '') }}-psycopg2{% endif %}"
  - postgresql{% if postgresql_version is defined and postgresql_version is not none and postgresql_version | string |
    length > 0 %}{{ postgresql_version | default('') }}{% endif %}

default_socket_path: /run/postgresql

hba_conf_path_alternative_cmd: >-
  printf "%s/pg_hba.conf" "$(grep -rn 'pgdata' /run/openrc/daemons/postgresql | sed -r 's/.*pgdata=//')"

postgresql_data_path: /var/lib/postgresql/{% if not (postgresql_version_regex is defined and postgresql_version_regex |
  length > 0) %}{{ postgresql_version }}/{% endif %}/data

postgresql_conf_path_alternative_cmd: >-
  printf "%s/postgresql.conf" "$(grep -rn 'data-directory' /run/openrc/daemons/postgresql |
  sed -r 's/.*data.directory=//' | sed -e 's/[[:space:]]$//')"
