---

# An example playbook to test and troubleshoot on developing. Try also:
# rm -f *.tar.gz; ansible-galaxy collection build; ansible-galaxy collection install $(ls -1 | grep ".tar.gz") -f
# ansible-playbook -i roles/bareos/inventory roles/bareos/install_bareos_fd_example.yml

- hosts: all
  become: True
  become_method: sudo
  gather_facts: True

  tasks:

    - name: "install bareos fd example | Include bareos role to uninstall Bareos director with Web UI"
      ansible.builtin.include_role:
        name: alexanderbazhenoff.linux.bareos
      vars:
        bareos_components: dir_webui
        postgresql_version: 14
        role_action: uninstall