---
- name: "purge repo redhat | Remove additional repo"
  ansible.builtin.file:
    path: /etc/yum.repos.d/lxc.repo
    state: absent

- name: "purge repo redhat | Disable addons repo (for container-selinux package)"
  ansible.builtin.ini_file:
    dest:
      /etc/yum.repos.d/{% if ansible_distribution_major_version | int == 7 %}oracle-linux{% else -%}
      public-yum{% endif %}-ol{{ ansible_distribution_major_version }}.repo
    section:
      "{% if ansible_distribution_major_version | int < 7 %}public_{% endif -%}
      ol{{ ansible_distribution_major_version }}_addons"
    option: enabled
    value: 0
    mode: 0644
  when: ansible_distribution == 'OracleLinux' and ansible_pkg_mgr == 'yum'
