---

- name: "check firewall redhat | Check firewalld is running"   # noqa command-instead-of-module
  ansible.builtin.command: systemctl is-active firewalld
  ignore_errors: true
  register: firewalld_state
  changed_when: false
