---

- name: "firewall control redhat | Add firewalld rule"
  ansible.posix.firewalld:
    port: "{{ firewall_port | default(postgresql_conf.port) }}/tcp"
    state: "{{ firewall_state | default(False) | ternary('enabled', 'disabled') }}"
    permanent: True
    immediate: True
  when: firewall_control and firewalld_state.stdout is defined and firewalld_state.stdout == 'active'
