---
- name: "add client | Get fqdn or hostname for add_component_name when undefined"
  ansible.builtin.set_fact:
    add_component_name: >-
      {% if ansible_fqdn is not none and ansible_fqdn | length > 0 %}{{ ansible_fqdn }}{% else %}{{ ansible_hostname -}}
      {% endif %}
  when: add_component_name is none or add_component_name | length == 0

- name: "add client | Get file daemons list from bareos server"
  ansible.builtin.shell: set -o pipefail; echo 'list clients' | bconsole
  args:
    executable: /bin/bash
  register: bconsole_list_results
  changed_when: false
  delegate_to: "{{ add_component_server | default(ansible_default_ipv4.address) }}"

- name: "add client | Cleanup previous client configs (clean install)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  when:
    bconsole_list_results.stdout is defined and add_component_name not in bconsole_list_results.stdout and
    not add_component_force
  with_items:
    - /etc/bareos/bareos-dir.d/client/{{ add_component_name }}.conf
    - /etc/bareos/bareos-dir-export/client/{{ add_component_name }}
  delegate_to: "{{ add_component_server | default(ansible_default_ipv4.address) }}"

- name: "add client | bconsole configure add {{ role_action.split('_') | last }}"
  ansible.builtin.shell: >-
    set -o pipefail;
    echo 'reload' | bconsole;
    echo 'configure add client name={{ add_component_name }} address={{ ansible_default_ipv4.address }}
    password={% if add_component_password is not none and add_component_password | length > 0 -%}
    {{ add_component_password }}{% else -%}
    {{ lookup('password', '/dev/null length={{ add_component_password_gen_length | int }} chars=ascii_letters') -}}
    {% endif %}
    tlsenable={{ add_component_tls_enable | lower }}' | bconsole;
    echo 'reload' | bconsole
  args:
    executable: /bin/bash
  register: bconsole_add_results
  failed_when:
    (bconsole_add_results.stdout is defined and 'configure error:' in bconsole_add_results.stdout) or
    (not add_component_force and bconsole_add_results.stdout is defined and bconsole_add_results.stdout |
    regex_search('Resource.*with name.*already exists')) or bconsole_add_results.failed
  changed_when: not bconsole_add_results.failed
  ignore_errors: true
  delegate_to: "{{ add_component_server | default(ansible_default_ipv4.address) }}"
  no_log: "{{ not (debug_mode | default(false)) }}"

- name: "add cleint | Warn when file daemon client already exists on bareos server"
  ansible.builtin.debug:
    msg: "WARNINIG! {{ add_component_name }} already exists on
      {{ add_component_server | default(ansible_default_ipv4.address) }}, trying to export an existing config."
  when: bconsole_add_results.stdout is defined and bconsole_add_results.stdout |
    regex_search('Resource.*with name.*already exists')

- name: "add client | Check file daemon config created or already exists on a server"
  ansible.builtin.stat:
    path: /etc/bareos/bareos-dir-export/client/{{ add_component_name }}/bareos-fd.d/director/bareos-dir.conf
  register: check_bareos_fd_config
  failed_when: not check_bareos_fd_config.stat.exists
  delegate_to: "{{ add_component_server | default(ansible_default_ipv4.address) }}"

- name: "add client | Insert TLS option in export content of the config on bareos server"
  ansible.builtin.lineinfile:
    path: /etc/bareos/bareos-dir-export/client/{{ add_component_name }}/bareos-fd.d/director/bareos-dir.conf
    insertbefore: "^}"
    line: "  TlsEnable = {{ add_component_tls_enable | lower }}"
  delegate_to: "{{ add_component_server | default(ansible_default_ipv4.address) }}"

- name: "add client | Get export content of the config from bareos server"
  ansible.builtin.slurp:
    src: /etc/bareos/bareos-dir-export/client/{{ add_component_name }}/bareos-fd.d/director/bareos-dir.conf
  register: bareos_export_config_data
  delegate_to: "{{ add_component_server | default(ansible_default_ipv4.address) }}"

- name: "add client | (debug) Show export content of the config from bareos server"
  ansible.builtin.debug:
    msg: "{{ bareos_export_config_data.content | b64decode }}"
  when: debug_mode | default(false)

- name: "add client | Export content of the config"
  ansible.builtin.copy:
    content: "{{ bareos_export_config_data.content | b64decode }}"
    dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
    force: true
    mode: 0640
    owner: bareos
    group: bareos
  notify:
    - bareos daemons restart

- name: "add client | Update config on file daemon"
  ansible.builtin.template:
    src: client.conf.j2
    dest: /etc/bareos/bareos-fd.d/client/myself.conf
    mode: 0640
    owner: root
    group: bareos
