---

- name: "enable start bareos redhat | Enable and start daemons via systemctl"
  ansible.builtin.command:
    cmd: systemctl enable --now {{ item }}   # noqa command-instead-of-module
  register: systemctl_results
  changed_when: not systemctl_results.failed
  when: item is defined and item is not none and item | length > 0
  with_items:
    - "{{ bareos_daemons | json_query(bareos_components) }}"
