---
- name: "install pre-requirements | Set pre-required packages list"
  ansible.builtin.set_fact:
    packages_to_install:
      - ca-certificates
      - "{% if ansible_os_family == 'Debian' %}apt-transport-https{% endif %}"
      - "{% if ansible_distribution != 'Fedora' and ansible_distribution_major_version | int >= 7 -%}
        {% if ansible_distribution == 'OracleLinux' %}oracle-epel-release-el{{ ansible_distribution_major_version -}}
        {% elif ansible_os_family == 'RedHat' %}epel-release{% endif %}{% endif %}"

- name: "install pre-requirements | Include install tasks depending on package manager"
  ansible.builtin.include_tasks: pkg_management/install_{{ ansible_pkg_mgr }}.yml
  when: ansible_os_family == 'RedHat'

- name: "install pre-requirements | Install pre-required packages with package generic module"
  ansible.builtin.package:
    name: "{{ item }}"
  when: ansible_os_family != 'RedHat' and item is defined and item is not none and item | length > 0
  register: pre_requirements_pkgs_results
  until: pre_requirements_pkgs_results is succeeded
  retries: 5
  delay: 5
  with_items:
    - "{{ packages_to_install }}"
