---
- name: "purge postgresql debian | Purge postgresql server (and psycopg2)"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    autoremove: true
    purge: true
  when: item is defined and item is not none and item | length > 0
  with_items:
    - "{{ postgresql_packages |
      json_query((ansible_os_family | lower) + (install_psycopg2 | ternary('_psycopg2', ''))) }}"

- name: "purge postgresql debian | Remove postgresql asc key and related files and folders"
  ansible.builtin.file:
    path: "{{ item | trim }}"
    state: absent
  with_items:
    - /etc/apt/keyrings/dgdg.asc
    - /var/lib/postgresql/{{ postgresql_version }}

- name: "purge postgresql debian | Install debian repository"
  ansible.builtin.apt_repository:
    repo: "{{ postgresql_debian_repo }}"
    state: absent
