---
- name: "purge bareos redhat | Set bareos packages list to uninstall"
  ansible.builtin.set_fact:
    packages_to_install:
      - "{{ bareos_packages | json_query(bareos_components) + install_additional_bareos_packages }}"
      - "{% if bareos_components | regex_search('webui') %}{{ php_package_dependencies }}{% endif %}"

- name: "purge bareos redhat | Include purge tasks depending on package manager"
  ansible.builtin.include_tasks: pkg_management/purge_{{ ansible_pkg_mgr }}.yml
