---

- name: "purge postgresql redhat | Include check repo url tasks"
  ansible.builtin.include_tasks: check_postgresql_repo_url_redhat.yml

- name: "purge postgresql redhat | Remove repository key"
  ansible.builtin.rpm_key:
    key: "{{ postgresql_url }}repos/yum/RPM-GPG-KEY-PGDG"
    state: absent
    validate_certs: false

- name: "purge postgresql redhat | Set postgresql server package(s) list"
  ansible.builtin.set_fact:
    packages_to_install:
      - "{{ postgresql_packages |
        json_query((ansible_os_family | lower) + (install_psycopg2 | ternary('_psycopg2', ''))) }}"

- name: "purge postgresql redhat | Include purge tasks depending on package manager"
  ansible.builtin.include_tasks: pkg_management/purge_{{ ansible_pkg_mgr }}.yml

- name: "purge postgresql redhat | Cleanup postgresql-related files and folders"
  ansible.builtin.file:
    path: /var/lib/pgsql/{{ postgresql_version }}/data
    state: absent
