---

- name: "delete zabbix agent pacman | Remove zabbix agent packages"
  community.general.pacman:
    name: "{{ item }}"
    state: absent
    force: true
    remove_nosave: true
  with_items:
    - zabbix-agent
    - zabbix-agent2
