---

- name: "delete zabbix agent apt | Remove zabbix agent packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    autoremove: true
    purge: true
  with_items:
    - zabbix-agent
    - zabbix-agent2
    - zabbix-release
