---

- name: "install zabbix agent archlinux | Getting index page from archive.archlinux.org"
  ansible.builtin.get_url:
    url: "{{ archlinux_repo_url_prefix }}/z/{{ zabbix_agent_daemon_name }}/"
    dest: /tmp/zabbix.html
    mode: 0644
    validate_certs: "{{ repo_dl_validate_certs | bool }}"

- name: "install zabbix agent archlinux | Filter index page for required zabbix release"
  ansible.builtin.shell: |
    set -e -o pipefail
    cat /tmp/zabbix.html | grep "{{ zabbix_release }}"
  args:
    executable: /bin/bash
  changed_when: False
  register: grep_zabbix_release

- name: "install zabbix agent archlinux | Set fact for extracted package filename"
  ansible.builtin.set_fact:
    package_filename: >-
      {{ grep_zabbix_release.stdout_lines | reject('search', '.sig') | last | regex_replace('(.+">)|(<\/a>.+)', '') -}}
  when: grep_zabbix_release.stdout_lines is defined and grep_zabbix_release.stdout_lines | length > 0

- name: "install zabbix agent archlinux | Checking that specified release available for linux distribution"
  ansible.builtin.assert:
    that:
      - package_filename is defined and package_filename | length > 0
    fail_msg: >-
      There is no 'zabbix-release' package version {{ zabbix_release }}. Please set another zabbix release.
    success_msg: "Found zabbix release package, URL: {{ archlinux_repo_url_prefix }}/z/{{ zabbix_agent_daemon_name -}}
      /{{ package_filename }}"

- name: "install zabbix agent archlinux | Download required zabbix-agent package"
  ansible.builtin.get_url:
    url: "{{ archlinux_repo_url_prefix }}/z/{{ zabbix_agent_daemon_name }}/{{ package_filename }}"
    dest: /tmp/{{ package_filename }}
    mode: 0644
    validate_certs: "{{ repo_dl_validate_certs | bool }}"

# When you install agent v1 6.2 on Arch Linux, this will also install agent v2 because of dependencies.
# So I put special clean-up of agent v1. Hope it helps. Otherwise, you can install using bsdtar like:
#  - name: "| Install zabbix-agent package using bsdtar (ArchLinux)"
#    ansible.builtin.command: bsdtar -C / -xvf /tmp/{{ package_filename }}
#  - name: "| Systemctl daemon reload (ArchLinux)"
#    ansible.builtin.command: systemctl daemon-reload

- name: "install zabbix agent archlinux | Install required zabbix-agent package"
  community.general.pacman:
    name: /tmp/{{ package_filename }}
    state: present

- name: "install zabbix agent archlinux | Remove zabbix agent v1 package (workaround of incorrect dependencies)"
  community.general.pacman:
    name: zabbix-agent
    state: absent
    force: True
  when: zabbix_agent_daemon_name == 'zabbix-agent2'
