---

- name: "main | Include delete zabbix agent tasks"
  include: delete_zabbix_agent_main.yml
  when: clean_install

- name: "main | Include install zabbix agent tasks"
  ansible.builtin.include_tasks: install_zabbix_agent_main.yml
  when: not customize_agent_only

- name: "main | Include reconfigure zabbix agent tasks"
  ansible.builtin.include_tasks: reconfigure_zabbix_agent.yml
  when: customize_agent
