---

- name: "destroy vm | shutdown instance"
  virt:
    name: "{{ vm_name }}"
    state: destroyed
  failed_when: False

- name: "destroy vm | remove instance"
  virt:
    name: "{{ vm_name }}"
    command: undefine
  failed_when: False

- name: "destroy vm | find VM image path"
  ansible.builtin.find:
    path: "{{ molecule_yml.driver.images_path }}"
    patterns: "{{ vm_name }}*"
  register: del_files

- name: "destroy vm | remove VM image"
  ansible.builtin.file:
    path: "{{ file.path }}"
    state: absent
  loop: "{{ del_files.files }}"
  loop_control:
    loop_var: file
