---
# Zabbix agent release:
zabbix_release: 5.0

# Install zabbix-agent v2 when possible (v2 is available in zabbix repo for current linux distribution):
install_v2_agent: true

# Customize agent for automatic services discovery and templates add:
customize_agent: true

# Delete all agents and config before install:
clean_install: true

# Lots of debug outputs:
debug_mode: false

# Force cleanup zabbix agent directories and files (just to avoid installation/uninstallation scripts bugs):
conf_with_dir_clean: true

# Only customize and configure already installed zabbix agent:
customize_agent_only: false

# Zabbix repo URL:
zabbix_repo_url: http://repo.zabbix.com

# Archlinux repo URL prefix:
archlinux_repo_url_prefix: https://archive.archlinux.org/packages

# Validate certs when downloading packages (to avoid failure on some outdated virtual machines snapshots):
repo_dl_validate_certs: false

# Parameters for zabbix agent settings
zabbix_agent_conf_name: zabbix_agentd
zabbix_agent_daemon_name: zabbix-agent
zabbix_agent_binary: zabbix-agent
remote_cmd_key: EnableRemoteCommands
remote_cmd_value: 1
logfile_size_key: LogFileSize
logfile_size_value: 100
# Specify Zabbix server(s) IP(s) for passive hosts discovery (e.g. '10.0.0.1,10.0.0.2'):
zabbix_servers_passive: 10.0.0.1,10.0.0.2
# Specify Zabbix server(s) IP(s) for active hosts discovery (e.g. '10.0.0.1:10051,10.0.0.2:10051'):
zabbix_servers_active: 10.0.0.1:10051,10.0.0.2:10051
zabbix_host_metadata: Linux

### services discovery parameters for templates add:

# binaries hashes:
binaries_tag_hashes:
  - name: java
    hash: dd6f76706e
  - name: openvpn
    hash: dd6a617661

# daemon hashes:
daemon_tag_hashes:
  - name: openvpn
    tag: ovpn # dd6f76706e
  - name: mysql
    tag: mysql # dd6d7973716c
  - name: mariadb
    tag: mysql # dd6d7973716c
  - name: postgresql
    tag: pgsql # dd706773716c
  - name: bareos-dir
    tag: brsdir # dd627273646972
  - name: bareos-fd
    tag: brsfd # dd6272736664
  - name: bareos-sd
    tag: brssd # dd6272737364
  - name: memcached
    tag: mmcchd # dd6d6d63636864
  - name: nginx
    tag: ngnx # dd6e676e78
  - name: php-fpm
    tag: pfpm # dd7066706d
  - name: httpd
    tag: apch # dd61706368
  - name: named
    tag: ndns # dd6e646e73
  - name: isc-dhcp-server
    tag: iscdhcp # dd69736364686370
  - name: dnsmasq
    tag: dnsm # dd646e736d
  - name: fail2ban
    tag: f2b # dd663262
  - name: vsftpd
    tag: vsftp # dd7673667470
  - name: gitlab-runner
    tag: gtrn # dd6774726e
  - name: nfs-server
    tag: nfs # dd6e6673
  - name: zabbix-agent
    tag: zba1 # dd7a626131
  - name: zabbix-agent2
    tag: zba2 # dd7a626132
