---

- name: restart zabbix-agent svc
  ansible.builtin.service:
    name: "{{ zabbix_agent_daemon_name }}"
    state: restarted
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 12) or
    (ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 9) or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 6) or
    ansible_os_family == "Archlinux"

- name: restart zabbix-agent sysv
  ansible.builtin.sysvinit:
    name: "{{ zabbix_agent_daemon_name }}"
    state: restarted
    enabled: True
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int < 12) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int < 9) or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version | int < 6)
