---

galaxy_info:
  role_name: bareos
  namespace: alexanderbazhenoff
  author: Aleksandr Bazhenov
  description: Install and configure Bareos components.
  license: BSD-3-Clause
  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - bareos
    - linux
    - backup
    - infrastructure
    - services
dependencies: []
