---
- name: "purge dnf | Purge packages"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    autoremove: true
  when: item | length > 0
  with_items:
    - "{{ packages_to_install }}"
