ARG image_platform
ARG image_tag
FROM ${image_platform}:${image_tag}

# Switch Centos to Centos Stream and make dnf cache
RUN if [ $(command -v dnf) ]; then dnf --disablerepo '*' --enablerepo extras swap centos-linux-repos centos-stream-repos -y; fi
RUN if [ $(command -v dnf) ]; then dnf distro-sync -y && dnf makecache; fi

RUN if [ $(command -v dnf) ]; then dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3; fi
RUN if [ $(command -v dnf) ]; then dnf --assumeyes install sudo bash iproute dbus && dnf clean all; fi

RUN if [ -z $(command -v dnf) ]; then yum makecache fast; fi
RUN if [ -z $(command -v dnf) ]; then yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl; fi
RUN if [ -z $(command -v dnf) ]; then yum install -y bash iproute dbus; fi
RUN if [ -z $(command -v dnf) ]; then sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi


SHELL [ "/bin/bash", "-c" ]

ENTRYPOINT [ "/lib/systemd/systemd" ]